<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Male_gender</name>
   <tag></tag>
   <elementGuidId>8b17788c-d1ca-4227-9c2c-fb849c3b1d9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='gender']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;gender&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6e5a616-874e-4502-9458-dd7dfb0f0031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>49c186a4-622b-4155-a324-799b60150b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>4336fad7-406d-4035-b694-8dec88248217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>bf05dbbe-571f-4746-a174-4f3e9b25e867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;easycont&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 text-left&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/div[1]/label[@class=&quot;radio-inline&quot;]/input[1]</value>
      <webElementGuid>780b6269-2960-4d7f-b98c-f0e35b7dc6ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='gender']</value>
      <webElementGuid>44fe3ac9-578b-48da-a547-f0c4c5487af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='easycont']/div/div[2]/div[2]/div[2]/div/label/input</value>
      <webElementGuid>bbd7b688-c6f9-428f-91ee-fc3e297b86b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/input</value>
      <webElementGuid>b11aaf05-ed1c-4479-a902-801ebcd3601b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'gender']</value>
      <webElementGuid>22032bf8-e1b0-43d3-97b5-eb8236bca13e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
