<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_currency</name>
   <tag></tag>
   <elementGuidId>1349472f-baa8-436c-a705-3b07dcbe9570</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='p-dropdown p-component p-inputwrapper']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-dropdown.p-component.p-inputwrapper.w-full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e57a942a-d479-4713-b53b-75541e4f7c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown p-component p-inputwrapper w-full</value>
      <webElementGuid>165efb85-09e8-4a04-b1ff-e639cfa30272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>p-emptylabel</value>
      <webElementGuid>31206f44-5c82-417c-88f5-c2a38e06dba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;p-overflow-hidden&quot;]/div[@class=&quot;p-dialog-mask p-component-overlay p-component-overlay-enter&quot;]/div[@class=&quot;p-dialog p-component p-fluid&quot;]/div[@class=&quot;p-dialog-content&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;field p-input-icon-right w-8&quot;]/div[@class=&quot;p-dropdown p-component p-inputwrapper w-full&quot;]</value>
      <webElementGuid>a0b43b8f-1f8d-470d-9366-f4a41c0dcdf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Group name'])[1]/following::div[1]</value>
      <webElementGuid>09120720-9f6f-42c4-8d1e-ab0998f2c472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Month'])[1]/following::div[2]</value>
      <webElementGuid>382f7cf2-00f1-4642-bf5b-683382ba921a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Title'])[1]/preceding::div[3]</value>
      <webElementGuid>4fade0f5-afd2-4642-aa0b-2aa89945c635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div[2]/div</value>
      <webElementGuid>b75414e9-4465-4bb3-8331-25c46d15b788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'p-emptylabel' or . = 'p-emptylabel')]</value>
      <webElementGuid>72a85ad3-54e5-4b10-900b-189487bcc121</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
