<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_30</name>
   <tag></tag>
   <elementGuidId>132d1bf3-2a0f-470d-ad1c-f1eae4988022</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[5]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[6]/td[2]/span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fd44c0c5-da00-426f-8eed-efc8f5f4fbe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ef1368f6-e5bc-4f61-9f75-a8a26e2edc14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>60cfc61c-b287-4853-b9cf-a9b54b69fcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;p-overflow-hidden&quot;]/div[@class=&quot;p-datepicker p-component&quot;]/div[@class=&quot;p-datepicker-group-container&quot;]/div[@class=&quot;p-datepicker-group&quot;]/div[@class=&quot;p-datepicker-calendar-container&quot;]/table[@class=&quot;p-datepicker-calendar&quot;]/tbody[1]/tr[5]/td[4]/span[1]</value>
      <webElementGuid>0b461455-1b21-47ca-8853-bce5f10f53eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[63]</value>
      <webElementGuid>2b32d8f3-2535-4b50-aaa7-f765e74bf37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[64]</value>
      <webElementGuid>ab3cd384-3131-40c5-9093-abb1cbe2b861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[4]/span</value>
      <webElementGuid>893b2323-ee1f-46ba-aedd-43a9e04a2147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '28' or . = '28')]</value>
      <webElementGuid>80e66477-7b4c-4f1c-90fb-064454456434</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
