<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Basic Salary</name>
   <tag></tag>
   <elementGuidId>095a4bf8-3506-48a7-8a87-0dc69f76c2d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div[3]/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/ul/li[1]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-treenode-content.p-treenode-selectable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d5ec6f38-d25d-49a3-be4b-e07881b4bb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-treenode-content p-treenode-selectable</value>
      <webElementGuid>2dcbd0db-5415-4114-bc37-e69a1abba447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f457cda6-9886-43c4-8fcb-4ef5ba096038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>bc432eab-fcb2-4f9e-ae8f-f246f8ee4eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>45d43669-5c8e-44b1-8b09-857547de38e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Basic Salary</value>
      <webElementGuid>d6037a2e-3ab0-47ac-9774-adea183832db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;layout-wrapper layout-static&quot;]/div[@class=&quot;layout-main-container&quot;]/div[@class=&quot;layout-main&quot;]/div[@class=&quot;p-tabview p-component tab-size&quot;]/div[@class=&quot;p-tabview-panels&quot;]/div[@class=&quot;p-tabview-panel&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;container-side&quot;]/div[@class=&quot;p-tree p-component p-tree-selectable p-tree-flex-scrollable&quot;]/div[@class=&quot;p-tree-wrapper&quot;]/ul[@class=&quot;p-tree-container&quot;]/li[@class=&quot;p-treenode p-treenode-leaf&quot;]/div[@class=&quot;p-treenode-content p-treenode-selectable&quot;]</value>
      <webElementGuid>682bf5e0-ea2f-4e15-95e9-ca36dbf109d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[3]/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/ul/li/div</value>
      <webElementGuid>478d3b5a-ebdc-451e-a0fe-0e2823e77ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Directories:'])[1]/following::div[6]</value>
      <webElementGuid>b22f4c85-bb46-453d-8c50-3fca392fb566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Processed:'])[1]/following::div[7]</value>
      <webElementGuid>0d437bda-7d46-48d5-a97c-2962cecec8a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overtime Pay'])[1]/preceding::div[1]</value>
      <webElementGuid>1ced6be1-d1ce-4bf4-acbc-7c09c15e4a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/div</value>
      <webElementGuid>fba1b07c-3306-4353-910d-3612279df9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Basic Salary' or . = 'Basic Salary')]</value>
      <webElementGuid>7d27110b-5411-45b5-81cd-78ea9f060844</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
