<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit PHP (300,003)</name>
   <tag></tag>
   <elementGuidId>0bf17d85-75e3-4156-b37d-a348047fe5b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@class='p-button p-component p-button-danger p-button-sm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e2a70cc-3a00-4bfb-aea3-503e93591df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button p-component p-button-danger p-button-sm</value>
      <webElementGuid>774949e7-024e-46a1-ac5b-990632b846ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>72048b48-fcb6-427b-b1cf-4d0a610f5712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria:haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>46bd757c-91bd-40e7-b6f0-744e241e14c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>overlay_panel</value>
      <webElementGuid>39a9d48a-6dff-4142-a836-6e50d44b8285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit PHP (300,003)</value>
      <webElementGuid>91c985fb-2f6e-4d09-a09e-e336c90f3102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;layout-wrapper layout-static&quot;]/div[@class=&quot;layout-main-container&quot;]/div[@class=&quot;layout-main&quot;]/div[@class=&quot;p-tabview p-component tab-size&quot;]/div[@class=&quot;p-tabview-panels&quot;]/div[@class=&quot;p-tabview-panel&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;container-content&quot;]/div[@class=&quot;p-card p-component&quot;]/div[@class=&quot;p-card-body&quot;]/div[@class=&quot;p-card-content&quot;]/div[@class=&quot;flex flex-wrap gap-3 justify-content-between&quot;]/div[@class=&quot;flex-grow-1&quot;]/div[@class=&quot;button-container&quot;]/div[2]/button[@class=&quot;p-button p-component p-button-danger p-button-sm&quot;]</value>
      <webElementGuid>c48ec790-37e2-48a9-ba6c-6ea7319f6243</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>09e6fd4b-fbd1-4e3d-956c-d15084813fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[3]/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div/div/div[2]/div/div[2]/button[2]</value>
      <webElementGuid>85af6969-d490-4419-8b45-3ced3b74e07a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm work done'])[1]/following::button[1]</value>
      <webElementGuid>a1829d4e-02cf-4f7f-8d83-53f2ecaf1099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear Data'])[1]/following::button[2]</value>
      <webElementGuid>1be6a6a5-9f7e-4766-9a1f-51e1d92e05ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total 3'])[1]/preceding::button[2]</value>
      <webElementGuid>912a2053-8e65-43c5-8e3c-e1005ceb7d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>003d0e0b-2794-402a-b864-e3357be18663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Submit PHP (300,003)' or . = 'Submit PHP (300,003)')]</value>
      <webElementGuid>c4c6eb2c-8618-4599-9a57-8b276ce1fd87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
