<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_Payroll Main Menu SalarySubmit</name>
   <tag></tag>
   <elementGuidId>2e2a84cf-5a29-4282-a0f0-578bbc453465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div[2]/div/ul/li[9]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>00fe4f5a-ee2a-44eb-bfe3-a47c5f134acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/salary/payroll/payroll-home-manage</value>
      <webElementGuid>1c089d00-d901-4d18-bcca-59764a725ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple</value>
      <webElementGuid>664bda4c-64c1-4709-8a3e-95b93a15c35e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>menu.salary.payrollHomeManage</value>
      <webElementGuid>f5d5c9d1-5303-49c0-9dc0-b3e93fe91f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>ef719ee3-2ae4-4ce9-9f0f-aa9e253040b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payroll Main Menu</value>
      <webElementGuid>12614415-21fd-4d3c-bddb-a7b2621b0757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[1]/div[@id=&quot;app&quot;]/div[@class=&quot;layout-wrapper layout-static&quot;]/div[@class=&quot;layout-sidebar&quot;]/div[@class=&quot;layout-menu-container&quot;]/ul[@class=&quot;layout-menu&quot;]/li[@class=&quot;layout-menuitem-category&quot;]/ul[1]/li[1]/a[@class=&quot;p-ripple&quot;]</value>
      <webElementGuid>f7664421-7047-463e-8255-2f6f80022c1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/div/ul/li[9]/ul/li/a</value>
      <webElementGuid>c76a6c48-a728-4e38-95f1-d4e09d357dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salary Submit'])[1]/following::a[1]</value>
      <webElementGuid>1f0a00d6-c34d-4273-a1ce-ebca5f52d91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payslip Details'])[1]/following::a[1]</value>
      <webElementGuid>3c8d721b-91a4-4379-80e2-2057abe4d06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Salary'])[1]/preceding::a[1]</value>
      <webElementGuid>d4fe1f10-f81f-4f3f-9821-7213e8eedaae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/salary/payroll/payroll-home-manage')]</value>
      <webElementGuid>cfa51c5b-62fe-4f0c-9c27-ebe94e2e0e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/ul/li/a</value>
      <webElementGuid>cbb31e48-4ce2-4f0a-8d80-4c7ef1b50513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/salary/payroll/payroll-home-manage' and (text() = 'Payroll Main Menu' or . = 'Payroll Main Menu')]</value>
      <webElementGuid>283afec8-8749-4455-b15a-9c6dbfb3dc3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
