<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Employee salary Details</name>
   <tag></tag>
   <elementGuidId>2612eecf-159b-4ad2-99be-ae42bd4d7f63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div[3]/div/div/div[2]/div/div/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1492bffe-7392-4f74-95e6-dd62cd1a7cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-tabview-title</value>
      <webElementGuid>b436d5c7-646d-440b-a961-fe4d49618dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employee salary Details</value>
      <webElementGuid>d52aad56-eb7c-4717-851c-74a8d0547247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;layout-wrapper layout-static&quot;]/div[@class=&quot;layout-main-container&quot;]/div[@class=&quot;layout-main&quot;]/div[1]/div[@class=&quot;p-tabview p-component&quot;]/div[@class=&quot;p-tabview-nav-container&quot;]/div[@class=&quot;p-tabview-nav-content&quot;]/ul[@class=&quot;p-tabview-nav&quot;]/li[2]/a[@class=&quot;p-tabview-nav-link&quot;]/span[@class=&quot;p-tabview-title&quot;]</value>
      <webElementGuid>99b3aba6-91ce-4417-8691-7c339450cd30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[3]/div/div/div[2]/div/div/ul/li[2]/a/span</value>
      <webElementGuid>29cda647-c82d-4233-a044-fdacbf8195ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department sum table'])[1]/following::span[2]</value>
      <webElementGuid>c55e86c8-f408-4ed3-9c65-f8b623d5c0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload end time：'])[1]/following::span[5]</value>
      <webElementGuid>05db1c02-1e8a-49fd-9e2f-ac7b5c0d416b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[1]/preceding::span[2]</value>
      <webElementGuid>12246bec-643d-4dc9-83e3-02328d2916ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export'])[1]/preceding::span[5]</value>
      <webElementGuid>bbde7321-7d82-45b2-b91c-be14aabab5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Employee salary Details']/parent::*</value>
      <webElementGuid>87f25000-5e26-4769-a059-804804829830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>487dd7cd-f83e-43a5-a450-9900cc63f6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Employee salary Details' or . = 'Employee salary Details')]</value>
      <webElementGuid>b17f8563-5235-49c0-92be-219fd9c5ef67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
