<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_calendar</name>
   <tag></tag>
   <elementGuidId>52316a1b-6d31-4b88-87d7-b56b09293e99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8d92db1-d27c-4769-bc78-31e737e6fe01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9059af95-1fff-4ac6-a476-d7d942c09fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component</value>
      <webElementGuid>dcab4b1f-4b87-4245-8f07-3315a2ecea79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Employee signature deadline</value>
      <webElementGuid>59f09d05-0389-4285-be57-452458af6bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>908864a3-6c3f-4917-8082-31b626ff4e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overlay_panel&quot;)/div[@class=&quot;p-overlaypanel-content&quot;]/div[1]/div[@class=&quot;field&quot;]/span[@class=&quot;p-calendar p-component p-inputwrapper p-calendar-w-btn p-inputwrapper-focus&quot;]/input[@class=&quot;p-inputtext p-component&quot;]</value>
      <webElementGuid>488a4bb9-5c43-47df-b822-bd121c3ca3f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>242965b0-4baf-4537-8e30-133dc83f95bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='overlay_panel']/div/div/div[2]/span/input</value>
      <webElementGuid>72a4dc7c-27c7-4893-a2a6-fa3320b036b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>449b93d2-24b9-49e1-a19c-d160acead7cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Employee signature deadline']</value>
      <webElementGuid>58310160-9d8e-4601-9e53-bb0f6bafa567</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
