<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>8530ebcc-8f82-434a-8263-adeb94af8e3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div[3]/div/div/div[2]/div/div/div/div/div/button/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-button-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>89970afc-6823-49c1-b8ef-8c0483899bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button-label</value>
      <webElementGuid>b2358454-d94b-4d1b-9c9d-323c6f776616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>1553b65e-053e-40c3-ac2f-608d9a10d27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;layout-wrapper layout-static&quot;]/div[@class=&quot;layout-main-container&quot;]/div[@class=&quot;layout-main&quot;]/div[1]/div[2]/div[@class=&quot;p-datatable p-component p-datatable-scrollable p-datatable-scrollable-vertical p-datatable-responsive-stack editable-cells-table&quot;]/div[@class=&quot;p-datatable-header&quot;]/div[1]/div[@class=&quot;flex justify-content-between flex-wrap align-items-center&quot;]/div[@class=&quot;flex&quot;]/button[@class=&quot;p-button p-component p-button-success mr-4&quot;]/span[@class=&quot;p-button-label&quot;]</value>
      <webElementGuid>04c86f42-35b5-47d1-b35e-04d452693284</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[3]/div/div/div[2]/div/div/div/div/div/button/span[2]</value>
      <webElementGuid>3488207f-6b33-4c04-855f-6b9232db2f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payroll group'])[1]/following::span[2]</value>
      <webElementGuid>b68bb431-f9fe-4671-992e-c403648e773a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Reported Errors'])[1]/following::span[3]</value>
      <webElementGuid>94f814c7-7750-4477-83a3-0945e348b1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/preceding::span[3]</value>
      <webElementGuid>c45b1c49-a18a-4d91-8e92-72feccc5c201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total 1'])[1]/preceding::span[8]</value>
      <webElementGuid>73303ff8-4d52-476c-8169-fd9ddcedc26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>0894a7f1-936b-4c00-8589-c6fa3845d32c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span[2]</value>
      <webElementGuid>48c9c637-76ec-4e8e-98c3-5e3ef0048c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>70ecfe4b-e02c-4f3e-82b5-6ddff332e117</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
