<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ApproverGroup</name>
   <tag></tag>
   <elementGuidId>a0760ad1-02fa-4fe0-a6e3-10d4d86f64f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[4]/div[1]/div[2]/div[2]/div[1]/div[4]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
