<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button2_AddCategory</name>
   <tag></tag>
   <elementGuidId>f19e9127-fdc9-4695-bc7a-9b2e4fae3408</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;app&quot;)/div[@class=&quot;layout-wrapper layout-static&quot;]/div[@class=&quot;layout-main-container&quot;]/div[@class=&quot;layout-main&quot;]/div[1]/div[1]/div[2]/div[@class=&quot;p-datatable p-component p-datatable-hoverable-rows p-datatable-scrollable p-datatable-scrollable-vertical p-datatable-responsive-stack editable-cells-table&quot;]/div[@class=&quot;p-datatable-header&quot;]/div[1]/div[@class=&quot;flex justify-content-between flex-wrap align-items-center&quot;]/div[@class=&quot;flex&quot;]/button[@class=&quot;p-button p-component p-button-success mr-4&quot;][count(. | //button[@class = 'p-button p-component p-button-success flex-grow-0 ml-0 mr-2' and @type = 'button' and (text() = 'Add' or . = 'Add') and @class = 'p-button p-component p-button-success flex-grow-0 ml-0 mr-2' and @type = 'button' and (text() = 'Add' or . = 'Add') and @class = 'p-button p-component p-button-success mr-4' and @type = 'button' and (text() = 'Add' or . = 'Add')]) = count(//button[@class = 'p-button p-component p-button-success flex-grow-0 ml-0 mr-2' and @type = 'button' and (text() = 'Add' or . = 'Add') and @class = 'p-button p-component p-button-success flex-grow-0 ml-0 mr-2' and @type = 'button' and (text() = 'Add' or . = 'Add') and @class = 'p-button p-component p-button-success mr-4' and @type = 'button' and (text() = 'Add' or . = 'Add')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@class='p-button p-component p-button-success flex-grow-0 ml-0 mr-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.p-button.p-component.p-button-success.flex-grow-0.ml-0.mr-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>954e18c1-e8ca-40f5-ad8b-e5b6aacdb85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>77549dc7-74b9-4842-9d2e-91b06029ea0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>d6532796-60d7-4041-9832-8add70373e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>5cdfa549-23c7-41ce-b3ef-0e715fe50537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>5bbcfc4c-762a-4eca-96cb-7285ed5a4e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>be7c1191-149e-4b17-b55d-25173565a1ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a603ff8b-f6a3-4cb0-9f3d-066c2cc42dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>716f615f-4f27-45f5-baef-acccdac66b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>198ba674-0215-499b-8509-94cec60159c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>cd19d872-4cff-4a6f-b93f-042a27dcbd3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/preceding::button[1]</value>
      <webElementGuid>811b6e43-15b6-4141-a9db-48a7bfbcc889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div/button</value>
      <webElementGuid>75363fbf-5c23-45d3-bd1b-542b17f73e57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
