<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Select Month</name>
   <tag></tag>
   <elementGuidId>2963f664-d140-49b2-a67e-76415d8d2fdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span/span/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.pi.pi-calendar.p-button-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a0ece42c-aa9c-4ef8-9435-51ee4da2a8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pi pi-calendar p-button-icon</value>
      <webElementGuid>85dac130-62c4-4c02-a1ca-b7ee5dc97e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;p-overflow-hidden&quot;]/div[@class=&quot;p-dialog-mask p-component-overlay p-component-overlay-enter&quot;]/div[@class=&quot;p-dialog p-component p-fluid&quot;]/div[@class=&quot;p-dialog-content&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;field p-input-icon-right mr-2&quot;]/span[@class=&quot;relative&quot;]/span[@class=&quot;p-calendar p-component p-inputwrapper p-calendar-w-btn&quot;]/button[@class=&quot;p-button p-component p-button-icon-only p-datepicker-trigger&quot;]/span[@class=&quot;pi pi-calendar p-button-icon&quot;]</value>
      <webElementGuid>ac1afb59-d6e0-4e2a-985a-967ec21c182d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/button/span</value>
      <webElementGuid>97c102d3-eab1-4f4f-ad61-d1e435700909</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
