<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Not configured permission</name>
   <tag></tag>
   <elementGuidId>c957f32d-a1bd-4e85-9577-0657b2c59317</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.w-full.w-full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdfbbef1-36ec-423a-85b8-50a08aec1eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component w-full w-full</value>
      <webElementGuid>bd370b21-a1b0-453f-ba15-490beb703b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e58de14b-714f-40d0-9974-f639025150b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>dd90170c-1276-4410-ac6d-f4807ed0d5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;p-overflow-hidden&quot;]/div[@class=&quot;p-sidebar p-component p-sidebar-right p-sidebar-active route-sidebar&quot;]/div[@class=&quot;p-sidebar-content&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col-5 md:col-12 lg:col-5&quot;]/div[@class=&quot;main p-2&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;p-input-icon-left w-full&quot;]/input[@class=&quot;p-inputtext p-component w-full w-full&quot;]</value>
      <webElementGuid>f811d1de-991f-4f2f-b630-5e56f7c823ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33721e20-b056-4381-964f-ce0a6e9280ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component w-full w-full</value>
      <webElementGuid>a919350c-02e2-46e9-b5db-450aef15555b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e8f0a207-cdf0-4dab-a9d8-2a4146927ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>cd4c8a24-6ba6-4ec7-b9ac-c3e91d16705f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;p-overflow-hidden&quot;]/div[@class=&quot;p-sidebar p-component p-sidebar-right p-sidebar-active route-sidebar&quot;]/div[@class=&quot;p-sidebar-content&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col-5 md:col-12 lg:col-5&quot;]/div[@class=&quot;main p-2&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;p-input-icon-left w-full&quot;]/input[@class=&quot;p-inputtext p-component w-full w-full&quot;]</value>
      <webElementGuid>d104a6c5-426a-485d-9133-e7940e16c49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b383792-3dfa-4cf7-a674-5e0b8bf5d083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component w-full w-full</value>
      <webElementGuid>8fae4e4c-5abb-4438-ac30-b534ecf83f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd5a28f9-4425-48ed-8ccc-bee8eb3613ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>70d3c3bb-caac-40d0-a463-759122d89a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;p-overflow-hidden&quot;]/div[@class=&quot;p-sidebar p-component p-sidebar-right p-sidebar-active route-sidebar&quot;]/div[@class=&quot;p-sidebar-content&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col-5 md:col-12 lg:col-5&quot;]/div[@class=&quot;main p-2&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;p-input-icon-left w-full&quot;]/input[@class=&quot;p-inputtext p-component w-full w-full&quot;]</value>
      <webElementGuid>ec2a8683-8382-43ff-98ab-62c2f7e3058d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>7779f9da-8055-402d-8805-48e313666906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>d7be5ad2-b82f-49bc-9145-c112275dd9de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search']</value>
      <webElementGuid>cda56cad-cfe9-4bfc-8151-780c97b7bf58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
