<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>e2f83a12-2fed-4067-b800-f36c4fdd896c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.p-input-icon-left.w-full.relative > input.p-inputtext.p-component.p-filled.w-full.w-full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fa9b246-e65e-447d-8d08-57afec5a7900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-filled w-full w-full</value>
      <webElementGuid>72aa3e2a-e70b-4b73-bd46-85ad98484f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d0789dae-8116-4757-8dd4-c363339089e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>46c0702c-c519-4185-b251-8bc4c5067d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;login-container flex h-screen p-8&quot;]/div[@class=&quot;login-form col-6 flex justify-content-center align-items-center flex-column relative&quot;]/div[@class=&quot;login-form__with-username text-center w-6 fadeinright animation-duration-300 animation-iteration-1 animation-linear&quot;]/form[@class=&quot;p-fluid&quot;]/div[@class=&quot;field col-12 relative&quot;]/span[@class=&quot;p-input-icon-left w-full relative&quot;]/input[@class=&quot;p-inputtext p-component p-filled w-full w-full&quot;]</value>
      <webElementGuid>2753ee35-e2c7-468e-83cf-2ea7def3e191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ca61bee-3d2f-4c06-ad98-6bf3543ca4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-filled w-full w-full</value>
      <webElementGuid>284e9b79-f9f3-452e-bf68-af0df2cdfa79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b169a895-39a5-4bd8-bf53-d044718e516e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>6cc44c7e-3d0b-46e5-9549-2a9736c4cf1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;login-container flex h-screen p-8&quot;]/div[@class=&quot;login-form col-6 flex justify-content-center align-items-center flex-column relative&quot;]/div[@class=&quot;login-form__with-username text-center w-6 fadeinright animation-duration-300 animation-iteration-1 animation-linear&quot;]/form[@class=&quot;p-fluid&quot;]/div[@class=&quot;field col-12 relative&quot;]/span[@class=&quot;p-input-icon-left w-full relative&quot;]/input[@class=&quot;p-inputtext p-component p-filled w-full w-full&quot;]</value>
      <webElementGuid>d91eefd4-ef7a-4172-9e60-cfbe2331b471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19a8a14b-b587-4a59-86af-e458eddc46f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-filled w-full w-full</value>
      <webElementGuid>ba59f079-a2b0-4f32-821a-e857e4189d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>bb17381a-1f53-4980-bb84-c7288e532e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>102c735d-f3f1-4695-a7c9-bf10f31178ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;login-container flex h-screen p-8&quot;]/div[@class=&quot;login-form col-6 flex justify-content-center align-items-center flex-column relative&quot;]/div[@class=&quot;login-form__with-username text-center w-6 fadeinright animation-duration-300 animation-iteration-1 animation-linear&quot;]/form[@class=&quot;p-fluid&quot;]/div[@class=&quot;field col-12 relative&quot;]/span[@class=&quot;p-input-icon-left w-full relative&quot;]/input[@class=&quot;p-inputtext p-component p-filled w-full w-full&quot;]</value>
      <webElementGuid>c05bca02-e539-4ffe-a374-2d831ec2c544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1cce62a6-7bb5-48b3-bd1d-c6e13e90c495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-filled w-full w-full</value>
      <webElementGuid>3f970bd1-5454-4f71-bb6d-dd22caad8cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>132ff518-1acb-4568-ab3e-e94d6648416d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>196501c5-10dd-416b-8256-9afe89e9f2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;login-container flex h-screen p-8&quot;]/div[@class=&quot;login-form col-6 flex justify-content-center align-items-center flex-column relative&quot;]/div[@class=&quot;login-form__with-username text-center w-6 fadeinright animation-duration-300 animation-iteration-1 animation-linear&quot;]/form[@class=&quot;p-fluid&quot;]/div[@class=&quot;field col-12 relative&quot;]/span[@class=&quot;p-input-icon-left w-full relative&quot;]/input[@class=&quot;p-inputtext p-component p-filled w-full w-full&quot;]</value>
      <webElementGuid>e5ad48dd-0321-4b28-a7d1-be26dab41fb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>a69074fc-0125-4d3b-bb5d-b4c64042aa63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/div[2]/form/div[2]/span/input</value>
      <webElementGuid>1dd3baa8-0ba0-4260-8aa3-9943bea68284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>ef61344f-4b59-4c90-b995-3b50d1028c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>56de31f8-673e-4767-a047-5af69eeb82cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
