<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_search</name>
   <tag></tag>
   <elementGuidId>0b41febc-7b7e-4714-b2a8-b90775d1db19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.p-column-filter.p-column-filter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71ee2cad-9a8e-41bd-b9f9-c91b1620ffc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-column-filter p-column-filter</value>
      <webElementGuid>5fd45f68-4016-41d3-b692-37804d78b879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>264e060b-7b24-49a9-94a1-ed45dc789687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>a8f03be9-b47d-4796-9a18-72c5066d7a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[1]/div[@class=&quot;p-column-filter-overlay p-component p-fluid p-column-filter-overlay-menu&quot;]/div[@class=&quot;p-column-filter-constraints&quot;]/div[@class=&quot;p-column-filter-constraint&quot;]/div[1]/input[@class=&quot;p-inputtext p-component p-column-filter p-column-filter&quot;]</value>
      <webElementGuid>e6033b9d-6518-473d-b351-051eb8e3c5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c09cde6-8d52-43ca-a1ec-43e0ceeff31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-column-filter p-column-filter</value>
      <webElementGuid>80ef9e98-6b9b-4cf8-84ad-873b188694f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>895f0bd6-a532-4806-9a69-dc84b0ef60f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>f3853436-ee28-4761-855a-f191c615004c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[1]/div[@class=&quot;p-column-filter-overlay p-component p-fluid p-column-filter-overlay-menu&quot;]/div[@class=&quot;p-column-filter-constraints&quot;]/div[@class=&quot;p-column-filter-constraint&quot;]/div[1]/input[@class=&quot;p-inputtext p-component p-column-filter p-column-filter&quot;]</value>
      <webElementGuid>ffb425f0-472f-419b-8b4d-07377bf78f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5478229b-f5c2-4fd1-ac06-14f71cbb55ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-column-filter p-column-filter</value>
      <webElementGuid>97272752-084f-4fa9-b94f-4e5e734d30a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>775e7c78-d557-4aa4-8316-6c51fcb1d898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>adf410b4-bd9d-4493-827f-3323b18bd4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[1]/div[@class=&quot;p-column-filter-overlay p-component p-fluid p-column-filter-overlay-menu&quot;]/div[@class=&quot;p-column-filter-constraints&quot;]/div[@class=&quot;p-column-filter-constraint&quot;]/div[1]/input[@class=&quot;p-inputtext p-component p-column-filter p-column-filter&quot;]</value>
      <webElementGuid>8456637c-e686-40df-a945-e2b8f8a63f1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>b256b3bc-4cde-4663-8664-c212460e3e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>bc37f2c0-aa73-482a-b5cb-0152a2fc3377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Name']</value>
      <webElementGuid>5e699d8f-9a52-4904-add5-bc66433b2a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>8b439a90-adf4-4afe-a11f-557896fca985</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
