<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>settext_ remark</name>
   <tag></tag>
   <elementGuidId>61d6ae0b-8700-45d8-a61c-89fafac8de02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.p-inputtext.p-component.p-filled</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[4]/div[1]/div[2]/div[1]/div[3]/span[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97541969-ac1e-4436-9e27-34a19936a389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-filled</value>
      <webElementGuid>7033c2cc-1a98-4e24-8ada-1bf3c2bfdbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>modelmodifiers</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>fdeee36d-4f43-4a12-9d27-7c3299b353a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;p-overflow-hidden&quot;]/div[@class=&quot;p-dialog-mask p-component-overlay p-component-overlay-enter&quot;]/div[@class=&quot;p-dialog p-component p-fluid&quot;]/div[@class=&quot;p-dialog-content&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;field p-input-icon-right mr-2&quot;]/span[@class=&quot;relative&quot;]/input[@class=&quot;p-inputtext p-component p-filled&quot;]</value>
      <webElementGuid>af2f6e23-1e23-4665-8cfe-ec7fc5776d97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div[2]/span/input</value>
      <webElementGuid>f61d74a1-531f-444f-9750-42c731cc8284</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
