<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textfield_Mina2</name>
   <tag></tag>
   <elementGuidId>40983e35-25d4-4817-b52f-d916c50b3014</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Not configured'])[1]/following::div[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.flex.align-items-center.mb-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f70d1981-edc4-43f2-b2c3-101b35dd26a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex align-items-center mb-3</value>
      <webElementGuid>679ec38b-10f6-42bd-8ca5-cb6571949256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mina2</value>
      <webElementGuid>3d004799-cd3c-4f25-9400-cce2015c645d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;p-overflow-hidden&quot;]/div[@class=&quot;p-sidebar p-component p-sidebar-right p-sidebar-active route-sidebar&quot;]/div[@class=&quot;p-sidebar-content&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;col-5 md:col-12 lg:col-5&quot;]/div[@class=&quot;main p-2&quot;]/div[@class=&quot;content-form mt-2 p-2&quot;]/div[@class=&quot;flex align-items-center mb-3&quot;]</value>
      <webElementGuid>029b7871-332e-49a8-ab55-dc8bf3386c0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not configured'])[1]/following::div[5]</value>
      <webElementGuid>c0735ea6-d573-4052-970b-54ab42bd93a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remark'])[12]/following::div[13]</value>
      <webElementGuid>4e4f3c09-20c2-4f72-afee-6c4afd8d2369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configured'])[1]/preceding::div[9]</value>
      <webElementGuid>5fbbd929-3da6-4722-9eac-61d213a3531e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/div/div/div[3]/div</value>
      <webElementGuid>d00b37ca-3154-412c-b4fe-282867b83461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Mina2' or . = 'Mina2')]</value>
      <webElementGuid>9ebf4370-99b0-4493-92bc-0af00931a6a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
